# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# permissions for end users to edit tfcmanagedmachinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tfcmanagedmachinepool-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-terraform-cloud
    app.kubernetes.io/part-of: cluster-api-provider-terraform-cloud
    app.kubernetes.io/managed-by: kustomize
  name: tfcmanagedmachinepool-editor-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tfcmanagedmachinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tfcmanagedmachinepools/status
  verbs:
  - get
